const i18Obj = {
    en: {
        myName: 'Simankova Olga',
        occupation: 'FRONTEND DEVELOPER',
        contact: 'CONTACT',
        skills: 'SKILLS',
        languages: 'LANGUAGES',
        langRu: 'Russian - Native',
        langEn: 'English - B2',
        references: 'REFERENCES',
        refAleh: 'Aleh Harnizonau (tg: @olegar87)',
        refAlehEpam: 'EPAM Software Engineer',
        education: 'EDUCATION',
        university: 'State University of Management',
        faculty: 'Transport and Logistics Management 2010',
        experience: 'EXPERIENCE',
        experience_ui: 'User interface development experience.',
        experience_react: 'Familiar with React/Redux, experience with SPA development.',
        experience_css: 'Excellent knowledge of HTML, CSS, SASS.',
        experience_layout: 'Development of adaptive, cross-browser, semantic layout.',
        experience_api: 'Experience working with REST API.',
        experience_db: 'Experience working with a database (MongoDB).',
        experience_test: 'Experience writing unit tests (Jest).',
        experience_webpack: 'Setting up a Webpack build experience.',
        experience_figma: 'Familiarity with Figma.',
        experience_scrum: 'Scrum/Kanban experience.',
        experience_bem: 'Knowledge of BEM methodology.',
        experience_communication: 'Excellent team communication skills.',
        projects: 'PROJECTS',
    },
    ru: {
        myName: 'Симанкова Ольга',
        occupation: 'FRONTEND РАЗРАБОТЧИК',
        contact: 'КОНТАКТЫ',
        skills: 'НАВЫКИ',
        languages: 'ЯЗЫКИ',
        langRu: 'Русский - родной',
        langEn: 'Английский - B2',
        references: 'РЕКОМЕНДАЦИИ',
        refAleh: 'Олег Гарнизонов (телеграм: @olegar87)',
        refAlehEpam: 'Мидл разработчик в EPAM',
        education: 'ОБРАЗОВАНИЕ',
        university: 'Государственный Университет Управления',
        faculty: 'Управление на транспорте 2010',
        experience: 'ОПЫТ',
        experience_ui: 'User interface development experience.',
        experience_react: 'Familiar with React/Redux, experience with SPA development.',
        experience_css: 'Excellent knowledge of HTML, CSS, SASS.',
        experience_layout: 'Development of adaptive, cross-browser, semantic layout.',
        experience_api: 'Experience working with REST API.',
        experience_db: 'Experience working with a database (MongoDB).',
        experience_test: 'Experience writing unit tests (Jest).',
        experience_webpack: 'Setting up a Webpack build experience.',
        experience_figma: 'Familiarity with Figma.',
        experience_scrum: 'Scrum/Kanban experience.',
        experience_bem: 'Knowledge of BEM methodology.',
        experience_communication: 'Excellent team communication skills.',
        projects: 'ПРОЭКТЫ',
    },
};
