const i18Obj = {
    en: {
        myName: 'Simankova Olga',
        occupation: 'FRONTEND DEVELOPER',
        contact: 'CONTACT',
        skills: 'SKILLS',
        languages: 'LANGUAGES',
        langRu: 'Russian - Native',
        langEn: 'English - B2',
        references: 'REFERENCES',
        refAleh: 'Aleh Harnizonau (tg: @olegar87)',
        refAlehEpam: 'EPAM Software Engineer',
    },
    ru: {
        myName: 'Симанкова Ольга',
        occupation: 'FRONTEND РАЗРАБОТЧИК',
        contact: 'КОНТАКТЫ',
        skills: 'НАВЫКИ',
        languages: 'ЯЗЫКИ',
        langRu: 'Русский - родной',
        langEn: 'Английский - B2',
        references: 'РЕКОМЕНДАЦИИ',
        refAleh: 'Олег Гарнизонов (телеграм: @olegar87)',
        refAlehEpam: 'Мидл разработчик в EPAM',
    },
};
